version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  ## This is for use in production
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./.docker/node/Dockerfile.node
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
  #   env_file:
  #     - .env
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./.docker/nginx/Dockerfile.nginx
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - api
